fix: Refactor laravel clear cache command

diff --git a/tc/app/laravel/cache/clear b/tc/app/laravel/cache/clear
--- a/tc/app/laravel/cache/clear
+++ b/tc/app/laravel/cache/clear
@@ -11,47 +11,8 @@ case "${__os_version}" in
     *)
 esac
 
-function laravel_cache_clear() {
-  __output=$( php artisan clear-compiled )
-  _error_code=$?
-  __MSG="Command: tcctl laravel cache clear"
-  __MSG+="$__output"
-  if [ "$_error_code" -eq "0" ]; then
-    echo "$__output"
-  else
-    _message "$__MSG" "error" "$_error_code"
-  fi
-
-  __output=$( eval "$__command" )
-  _error_code=$?
-  __MSG="Command: $__command"
-  if [[ "$_error_code" -eq "0" ]]; then
-    echo "Command: $__command successfull"
-  else
-    _message "$__MSG" "error" "$_error_code"
-  fi
-
-  __output=$( php artisan config:cache )
-  _error_code=$?
-  __MSG="Command: tcctl laravel cache clear"
-  __MSG+="$__output"
-  if [ "$_error_code" -eq "0" ]; then
-    echo "$__output"
-  else
-    _message "$__MSG" "error" "$_error_code"
-  fi
-
-  __output=$( php artisan route:cache )
-  _error_code=$?
-  __MSG="Command: tcctl laravel cache clear"
-  __MSG+="$__output"
-  if [ "$_error_code" -eq "0" ]; then
-    echo "$__output"
-  else
-    _message "$__MSG" "error" "$_error_code"
-  fi
-
-  __output=$( php artisan event:cache )
+function check_exit_code {
+  __output=$( $1 )
   _error_code=$?
   __MSG="Command: tcctl laravel cache clear"
   __MSG+="$__output"
@@ -62,4 +23,20 @@ function laravel_cache_clear() {
   fi
 }
 
-laravel_cache_clear
+function reload_php_fpm {
+  __output=$( eval "$__command" )
+  _error_code=$?
+  __MSG="Command: $__command"
+  if [[ "$_error_code" -eq "0" ]]; then
+    echo "Command: $__command successfull"
+  else
+    _message "$__MSG" "error" "$_error_code"
+  fi
+}
+
+check_exit_code "php artisan clear-compiled"
+reload_php_fpm
+check_exit_code "php artisan config:cache"
+check_exit_code "php artisan route:cache"
+check_exit_code "php artisan event:cache"
+
