remove commands export

diff --git a/tc/app/laravel/scheduler/add b/tc/app/laravel/scheduler/add
--- a/tc/app/laravel/scheduler/add
+++ b/tc/app/laravel/scheduler/add
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
 
-# shellcheck source="$CLI_DIR/tc/framework/functions"
-# shellcheck source="$CLI_DIR/tc/app/aws/functions"
 # shellcheck disable=SC1090,SC2196,SC2120
 
 source "$CLI_DIR/tc/framework/functions"
@@ -12,33 +10,33 @@ function add_scheduler() {
   if [[ $OS == Linux ]] && [[ $( /etc/crontab | egrep -v "^(#|$)" | grep -q "$SCHEDULE_COMMAND"; echo $?) == 1 ]]
   then
     __output_1=$( "# Add scheduler for horizon-$PROJECT_NAME" )
-    export _error_code=$?
+    _error_code=$?
     __MSG="Command: \033[36mtcctl add $2 cron scheduler\033[39m\n"
     __MSG+="$__output_1"
     if [[ $_error_code -eq "0" ]]; then
       echo "# Add scheduler for horizon-$PROJECT_NAME" | sudo tee -a /etc/crontab > /dev/null 2>&1
     else
-      _message_error "$__MSG"
+      _message "$__MSG" "error" "$_error_code"
     fi
     __output_2=$( "* * * * * $USER $(command -v php) $SCHEDULE_COMMAND" )
-    export _error_code=$?
+    _error_code=$?
     __MSG="Command: \033[36mtcctl add $2 cron scheduler\033[39m\n"
     __MSG+="$__output_2"
     if [[ $_error_code -eq "0" ]]; then
       echo "* * * * * $USER $(command -v php) $SCHEDULE_COMMAND" | sudo tee -a /etc/crontab > /dev/null 2>&1
     else
-      _message_error "$__MSG"
+      _message "$__MSG" "error" "$_error_code"
     fi
   elif [[ $OS == Darwin ]] && [[ $(crontab -l | grep -q "$SCHEDULE_COMMAND"; echo $?) == 1 ]]
   then
     __output=$( "* * * * * $(command -v php) $SCHEDULE_COMMAND" )
-    export _error_code=$?
+    _error_code=$?
     __MSG="Command: \033[36mtcctl add $2 cron scheduler\033[39m\n"
     __MSG+="$__output"
     if [[ $_error_code -eq "0" ]]; then
       echo "* * * * * $(command -v php) $SCHEDULE_COMMAND" | crontab -
     else
-      _message_error "$__MSG"
+      _message "$__MSG" "error" "$_error_code"
     fi
   fi
 }
diff --git a/tc/app/service/status b/tc/app/service/status
--- a/tc/app/service/status
+++ b/tc/app/service/status
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
 
-# shellcheck source="$CLI_DIR/tc/framework/functions"
-# shellcheck source="$CLI_DIR/tc/app/aws/functions"
 # shellcheck disable=SC1090
 
 source "$CLI_DIR/tc/framework/functions"
@@ -23,29 +21,29 @@ esac
 done
 
 function status_service() {
-    SERVICE_NAME=$1
-    OS=$( _get_os )
-    if [[ $OS == Linux ]]; then
-      __output=$( systemctl is-active "$SERVICE_NAME" )
-      export _error_code=$?
-      __MSG="Command: tcctl service $1 status"
-      __MSG+="$__output"
-      if [[ $_error_code -eq "0" ]]; then
-        systemctl is-active "$SERVICE_NAME" | column -t
-      else
-        _message "$__MSG" "error" "$_error_code"
-      fi
-    elif [[ $OS == Darwin ]]; then
-      __output=$( $SERVICE_NAME status )
-      export _error_code=$?
-      __MSG="Command: mtcctl service $1 status"
-      __MSG+="$__output"
-      if [[ $_error_code -eq "0" ]]; then
-        $SERVICE_NAME status | awk '{ print $2 }'
-      else
-        _message "$__MSG" "error" "$_error_code"
-      fi
+  SERVICE_NAME=$1
+  OS=$( _get_os )
+  if [[ $OS == Linux ]]; then
+    __output=$( systemctl is-active "$SERVICE_NAME" )
+    _error_code=$?
+    __MSG="Command: tcctl service $1 status"
+    __MSG+="$__output"
+    if [[ $_error_code -eq "0" ]]; then
+      systemctl is-active "$SERVICE_NAME" | column -t
+    else
+      _message "$__MSG" "error" "$_error_code"
     fi
+  elif [[ $OS == Darwin ]]; then
+    __output=$( $SERVICE_NAME status )
+    _error_code=$?
+    __MSG="Command: mtcctl service $1 status"
+    __MSG+="$__output"
+    if [[ $_error_code -eq "0" ]]; then
+      $SERVICE_NAME status | awk '{ print $2 }'
+    else
+      _message "$__MSG" "error" "$_error_code"
+    fi
+  fi
 }
 
 if [ -z "$SERVICE_NAME" ]; then
