cmd, helpers commands refactoring

diff --git a/tc/app/helpers/env/get b/tc/app/helpers/env/get
--- a/tc/app/helpers/env/get
+++ b/tc/app/helpers/env/get
@@ -1,27 +1,56 @@
 #!/usr/bin/env bash
 
+# shellcheck disable=SC1090
+
 source "$CLI_DIR/tc/framework/functions"
 
+ENV="${ENV:-.env}"
+
+set +e
+
+while [[ $# -gt 0 ]]
+do
+key="$1"
+
+case $key in
+    --key)
+    KEY="$2"
+    shift 2
+    ;;
+    --env)
+    ENV="$2"
+    shift 2
+    ;;
+    *)
+    ;;
+esac
+done
+
 function get_value_from_env() {
-    VARIABLE=$1
-    FILENAME=$2
-    if [[ ! -f "$2" ]]; then
-      FILENAME=".env"
-    fi
-    __output=$( sed -n -e "s/^\s*$VARIABLE\s*=//p" $FILENAME )
-    export _error_code=$?
-    __MSG="Command: \033[36mtcctl helpers get value from $1\033[39m\n"
-    __MSG+="$__output"
-    if [ $_error_code -eq "0" ]; then
-      if [[ -z "$__output" ]]; then
-        _message_warning "$__MSG"
-        exit 1
-      else
-        echo $__output
-      fi
+  KEY=$1
+  ENV=$2
+  if [[ ! -f "$2" ]]; then
+    _message "$__MSG" "error" "$_error_code"
+  fi
+  __output=$( sed -n -e "s/^\s*$KEY\s*=//p" "$ENV" )
+  export _error_code=$?
+  __MSG="Command: tcctl helpers get value from $1"
+  __MSG+="$__output"
+  if [ $_error_code -eq "0" ]; then
+    if [[ -z "$__output" ]]; then
+      _message "$__MSG" "warning" "$_error_code"
+      exit 1
     else
-      _message_error "$__MSG"
+      echo "$__output"
     fi
+  else
+    _message "$__MSG" "error" "$_error_code"
+  fi
 }
 
-get_value_from_env $1 $2
+if [ -z "$KEY" ]; then
+  __MSG="Command: tcctl helpers env get missed --key"
+  _message "$__MSG" "error" "$_error_code"
+else
+  get_value_from_env "$KEY" "$ENV"
+fi
