fix: Stdout output to screan and variable

diff --git a/tc/app/run b/tc/app/run
--- a/tc/app/run
+++ b/tc/app/run
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# shellcheck disable=SC1090
+# shellcheck disable=SC1091
 
 source "$CLI_DIR/tc/framework/functions"
 
@@ -8,13 +8,13 @@ for __param in "$@"; do
   __parameters+="$__param "
 done
 
-__output="$( $__parameters >&2>&1 )"
-_error_code=$?
+__output="$( $__parameters 2>&1 | tee /dev/fd/5; exit "${PIPESTATUS[0]}")"
+__error_code=$?
 __MSG="Command: cmd run $__parameters"
 __MSG+="$__output"
 
-if [ "$_error_code" -eq "0" ]; then
+if [ "$__error_code" -eq "0" ]; then
   echo "$__output"
 else
-  _message "$__MSG" "error" "$_error_code"
+  _message "$__MSG" "error" "$__error_code"
 fi
