feature: Added command to change DB_SLAVE_HOST in .env file

diff --git a/tc/app/aws/functions b/tc/app/aws/functions
--- a/tc/app/aws/functions
+++ b/tc/app/aws/functions
@@ -72,3 +72,20 @@ function _delete_old_ecr_images() {
     _message "$__MSG" "error" "$__output"
   fi
 }
+
+# Get replicas name
+function get_replicas_name() {
+  __db_identifier=$1
+  __output=$( aws rds describe-db-instances --db-instance-identifier "$__db_identifier" )
+  _error_code=$?
+  __MSG="Command: tcctl aws $1 describe-db-instances"
+  __MSG+="$__output"
+  if [[ "$_error_code" -eq "0" ]]; then
+    __replica_db_instances=$( aws rds describe-db-instances --db-instance-identifier "$__db_identifier" | jq -r '.DBInstances[].ReadReplicaDBInstanceIdentifiers[]' )
+    for i in $__replica_db_instances; do
+      echo "$i"
+    done
+  else
+    _message "$__MSG" "error" "$_error_code"
+  fi
+}
