aws commands refactoring

diff --git a/tc/app/aws/get_db_identifier b/tc/app/aws/get_db_identifier
--- a/tc/app/aws/get_db_identifier
+++ b/tc/app/aws/get_db_identifier
@@ -1,23 +1,43 @@
 #!/usr/bin/env bash
 
-# shellcheck disable=SC1091
-# shellcheck source=../../framework/functions
-source "${CLI_DIR}/tc/framework/functions"
+# shellcheck disable=SC1090,SC2143
+
+source "$CLI_DIR/tc/framework/functions"
+
+set +e
+
+while [[ $# -gt 0 ]]
+do
+key="$1"
+
+case $key in
+    --db-master-name)
+    DB_MASTER_NAME="$2"
+    shift 2
+    ;;
+    *)
+    ;;
+esac
+done
 
 function get_db_identifier() {
-  NAME="$1"
-  if [[ -z $( echo $NAME | grep ".*\.amazonaws.com" ) ]]; then
-    __output="$( dig cname "$NAME" +short )"
-    export _error_code=$?
-    __MSG="Command: \033[36mtcctl aws $1 get_db_identifier\033[39m\n"
+  DB_MASTER_NAME="$1"
+  if [[ -z $( echo "$DB_MASTER_NAME" | grep ".*\.amazonaws.com" ) ]]; then
+    __output="$( dig cname "$DB_MASTER_NAME" +short )"
+    _error_code=$?
+    __MSG="Command: tcctl aws $1 get_db_identifier"
     __MSG+="$__output"
     if [[ $_error_code -eq "0" ]]; then
       echo "$__output" | awk -F '.' '{print $1}'
     else
-      _message_error "$__MSG"
+      _message "$__MSG" "error" "$_error_code"
     fi
   fi
 }
 
-get_db_identifier "$1"
-
+if [ -z "$DB_MASTER_NAME" ]; then
+  __MSG="Command: tcctl aws get_db_identifier missed --db-master-name"
+  _message "$__MSG" "error" "$_error_code"
+else
+  get_db_identifier "$DB_MASTER_NAME"
+fi
diff --git a/tc/app/aws/promote_master_replicas b/tc/app/aws/promote_master_replicas
--- a/tc/app/aws/promote_master_replicas
+++ b/tc/app/aws/promote_master_replicas
@@ -1,25 +1,48 @@
 #!/usr/bin/env bash
 
+# shellcheck disable=SC2155
+
 source "./cli/tc/framework/functions"
 
+set +e
+
+while [[ $# -gt 0 ]]
+do
+key="$1"
+
+case $key in
+    --db-master-name)
+    DB_MASTER_NAME="$2"
+    shift 2
+    ;;
+    *)
+    ;;
+esac
+done
+
 function promote_master_replicas() {
-  DB_IDENTIFIER=$1
-  __output=$( aws rds describe-db-instances --db-instance-identifier $DB_IDENTIFIER )
-  export _error_code=$?
-  __MSG="Command: \033[36mtcctl aws $1 describe-db-instances\033[39m\n"
+  DB_MASTER_NAME=$1
+  __output=$( aws rds describe-db-instances --db-instance-identifier "$DB_MASTER_NAME" )
+  _error_code=$?
+  __MSG="Command: tcctl aws $1 describe-db-instances"
   __MSG+="$__output"
   if [[ $_error_code -eq "0" ]]; then
     REPLICA_DB_INSTANCES=$( $__output | jq -r '.DBInstances[].ReadReplicaDBInstanceIdentifiers[]' )
-    export REPLICA_DB_INSTANCES_COUNT=$(echo $REPLICA_DB_INSTANCES | wc -w)
+    export REPLICA_DB_INSTANCES_COUNT=$(echo "$REPLICA_DB_INSTANCES" | wc -w)
     for i in $REPLICA_DB_INSTANCES; do
-      echo "Promote read replica $i to Instance"
+      echo "Promote read replica $i to instance"
       aws rds promote-read-replica \
-            --db-instance-identifier $i \
+            --db-instance-identifier "$i" \
             --backup-retention-period 1
     done
   else
-    _message_error "$__MSG"
+    _message "$__MSG" "error" "$_error_code"
   fi
 }
 
-promote_master_replicas $1
+if [ -z "$DB_MASTER_NAME" ]; then
+  __MSG="Command: tcctl aws promote_master_replicas missed --db-master-name"
+  _message "$__MSG" "error" "$_error_code"
+else
+  promote_master_replicas "$DB_MASTER_NAME"
+fi
