vault commands refactoring 3.0

diff --git a/tc/app/vault/diff b/tc/app/vault/diff
--- a/tc/app/vault/diff
+++ b/tc/app/vault/diff
@@ -13,12 +13,12 @@ do
 key="$1"
 
 case $key in
-    --env)
-    ENV="$2"
+    --env-1)
+    ENV1="$2"
     shift 2
     ;;
-    --env-tmp)
-    ENV_TEMP="$2"
+    --env-2)
+    ENV2="$2"
     shift 2
     ;;
     *)
@@ -26,19 +26,26 @@ case $key in
 esac
 done
 
-function vault_diff() {
-  tcctl helpers check_bin_file vault
-  ENV_FILE=$1
-  ENV_TEMP=$2
-  __output=$( diff -y --suppress-common-lines "$ENV_FILE" "$ENV_TEMP" )
-  export _error_code=$?
-  __MSG="Command: \033[36mtcctl vault diff $@\033[39m\n"
-  __MSG+="$__output"
-  if [[ $_error_code -eq "0" ]]; then
-    echo "$__output" | column -t
-  else
-    _message "$__MSG" "error" "$_error_code"
-  fi
-}
-
-vault_diff "$ENV" "$ENV_TEMP"
+if [ -z "$ENV1" ]; then
+  __MSG="Command: \033[36mtcctl vault diff\033[39m missed --env-1"
+  _message_error "$__MSG"
+elif [ -z "$ENV2" ]; then
+  __MSG="Command: \033[36mtcctl vault diff\033[39m missed --env-2"
+  _message_error "$__MSG"
+else
+  function vault_diff() {
+    tcctl helpers check_bin_file vault
+    ENV1=$1
+    ENV2=$2
+    __output=$( diff -y --suppress-common-lines "$ENV1" "$ENV2" )
+    export _error_code=$?
+    __MSG="Command: \033[36mtcctl vault diff $@\033[39m\n"
+    __MSG+="$__output"
+    if [[ $_error_code -eq "0" ]]; then
+      echo "$__output" | column -t
+    else
+      _message "$__MSG" "error" "$_error_code"
+    fi
+  }
+  vault_diff "$ENV1" "$ENV2"
+fi
