vault, laravel, php, service commands refactoring

diff --git a/tc/app/service/status b/tc/app/service/status
--- a/tc/app/service/status
+++ b/tc/app/service/status
@@ -22,18 +22,35 @@ case $key in
 esac
 done
 
-if [ -z "$SERVICE_NAME" ]; then
-  __MSG="Command: \033[36mtcctl service status\033[39m missed --service-name"
-  _message_error "$__MSG"
-else
-  function status_service() {
+function status_service() {
     SERVICE_NAME=$1
     OS=$( _get_os )
     if [[ $OS == Linux ]]; then
-      systemctl is-active "$SERVICE_NAME" | column -t
+      __output=$( systemctl is-active "$SERVICE_NAME" )
+      export _error_code=$?
+      __MSG="Command: tcctl service $1 status"
+      __MSG+="$__output"
+      if [[ $_error_code -eq "0" ]]; then
+        systemctl is-active "$SERVICE_NAME" | column -t
+      else
+        _message "$__MSG" "error" "$_error_code"
+      fi
     elif [[ $OS == Darwin ]]; then
-      $SERVICE_NAME status | awk '{ print $2 }'
+      __output=$( $SERVICE_NAME status )
+      export _error_code=$?
+      __MSG="Command: mtcctl service $1 status"
+      __MSG+="$__output"
+      if [[ $_error_code -eq "0" ]]; then
+        $SERVICE_NAME status | awk '{ print $2 }'
+      else
+        _message "$__MSG" "error" "$_error_code"
+      fi
     fi
-  }
+}
+
+if [ -z "$SERVICE_NAME" ]; then
+  __MSG="Command: Command: tcctl service status missed --service-name"
+  _message "$__MSG" "error" "$_error_code"
+else
   status_service "$SERVICE_NAME"
 fi
diff --git a/tc/app/service/stop b/tc/app/service/stop
--- a/tc/app/service/stop
+++ b/tc/app/service/stop
@@ -22,35 +22,36 @@ case $key in
 esac
 done
 
-if [ -z "$SERVICE_NAME" ]; then
-  __MSG="Command: \033[36mtcctl service stop\033[39m missed --service-name"
-  _message_error "$__MSG"
-else
-  function stop_service() {
-    SERVICE_NAME=$1
-    OS=$( _get_os )
-    if [[ $OS == Linux ]]; then
-      SUDO_COMMAND="sudo "
-      __output=$( $SUDO_COMMAND service "$SERVICE_NAME" stop )
-      export _error_code=$?
-      __MSG="Command: \033[36mtcctl service $1 stop\033[39m\n"
-      __MSG+="$__output"
-      if [[ $_error_code -eq "0" ]]; then
-        echo "$__output" | column -t
-      else
-        _message_error "$__MSG"
-      fi
-    elif [[ $OS == Darwin ]]; then
-      __output=$( $SERVICE_NAME stop all )
-      export _error_code=$?
-      __MSG="Command: \033[36mtcctl service $1 stop\033[39m\n"
-      __MSG+="$__output"
-      if [[ $_error_code -eq "0" ]]; then
-        echo "$__output" | column -t
-      else
-        _message_error "$__MSG"
-      fi
+function stop_service() {
+  SERVICE_NAME=$1
+  OS=$( _get_os )
+  if [[ $OS == Linux ]]; then
+    SUDO_COMMAND="sudo "
+    __output=$( $SUDO_COMMAND service "$SERVICE_NAME" stop )
+    export _error_code=$?
+    __MSG="Command: \033[36mtcctl service $1 stop\033[39m\n"
+    __MSG+="$__output"
+    if [[ $_error_code -eq "0" ]]; then
+      echo "$__output" | column -t
+    else
+      _message "$__MSG" "error" "$_error_code"
     fi
-  }
+  elif [[ $OS == Darwin ]]; then
+    __output=$( $SERVICE_NAME stop all )
+    export _error_code=$?
+    __MSG="Command: \033[36mtcctl service $1 stop\033[39m\n"
+    __MSG+="$__output"
+    if [[ $_error_code -eq "0" ]]; then
+      echo "$__output" | column -t
+    else
+      _message "$__MSG" "error" "$_error_code"
+    fi
+  fi
+}
+
+if [ -z "$SERVICE_NAME" ]; then
+  __MSG="Command: tcctl service stop missed --service-name"
+  _message "$__MSG" "error" "$_error_code"
+else
   stop_service "$SERVICE_NAME"
 fi
diff --git a/tc/app/service/update b/tc/app/service/update
--- a/tc/app/service/update
+++ b/tc/app/service/update
@@ -22,36 +22,37 @@ case $key in
 esac
 done
 
-if [ -z "$SERVICE_NAME" ]; then
-  __MSG="Command: \033[36mtcctl service update\033[39m missed --service-name"
-  _message_error "$__MSG"
-else
-  function update_service() {
-    SERVICE_NAME=$1
-    OS=$( _get_os )
-    if [[ $OS == Linux ]]; then
-      SUDO_COMMAND="sudo "
-      __output=$( $SUDO_COMMAND "$SERVICE_NAME" update )
-      export _error_code=$?
-      __MSG="Command: \033[36mtcctl service $1 update\033[39m\n"
-      __MSG+="$__output"
-      if [[ $_error_code -eq "0" ]]; then
-        $SUDO_COMMAND "$SERVICE_NAME" force-reload | column -t
-      else
-        _message_error "$__MSG"
-      fi
-    elif [[ $OS == Darwin ]]; then
-      SUDO_COMMAND=""
-      __output=$( $SUDO_COMMAND "$SERVICE_NAME" update )
-      export _error_code=$?
-      __MSG="Command: \033[36mtcctl service $1 update\033[39m\n"
-      __MSG+="$__output"
-      if [[ $_error_code -eq "0" ]]; then
-        $SUDO_COMMAND "$SERVICE_NAME" update | column -t
-      else
-        _message_error "$__MSG"
-      fi
+function update_service() {
+  SERVICE_NAME=$1
+  OS=$( _get_os )
+  if [[ $OS == Linux ]]; then
+    SUDO_COMMAND="sudo "
+    __output=$( $SUDO_COMMAND "$SERVICE_NAME" update )
+    export _error_code=$?
+    __MSG="Command: tcctl service $1 update"
+    __MSG+="$__output"
+    if [[ $_error_code -eq "0" ]]; then
+      $SUDO_COMMAND "$SERVICE_NAME" force-reload | column -t
+    else
+      _message "$__MSG" "error" "$_error_code"
     fi
-  }
+  elif [[ $OS == Darwin ]]; then
+    SUDO_COMMAND=""
+    __output=$( $SUDO_COMMAND "$SERVICE_NAME" update )
+    export _error_code=$?
+    __MSG="Command: tcctl service $1 update"
+    __MSG+="$__output"
+    if [[ $_error_code -eq "0" ]]; then
+      $SUDO_COMMAND "$SERVICE_NAME" update | column -t
+    else
+      _message "$__MSG" "error" "$_error_code"
+    fi
+  fi
+}
+
+if [ -z "$SERVICE_NAME" ]; then
+  __MSG="Command: tcctl service update missed --service-name"
+  _message "$__MSG" "error" "$_error_code"
+else
   update_service "$SERVICE_NAME"
 fi
diff --git a/tc/app/vault/config b/tc/app/vault/config
--- a/tc/app/vault/config
+++ b/tc/app/vault/config
@@ -2,13 +2,13 @@
 
 # shellcheck source="$CLI_DIR/tc/framework/functions"
 # shellcheck source="$CLI_DIR/tc/app/aws/functions"
-# shellcheck disable=SC2124,SC2129
+# shellcheck disable=SC2124,SC2129,SC2154
 
 source "$CLI_DIR/tc/framework/functions"
 
 VAULT_CONFIG_FILE=~/.vault-configuration
 COMMAND_SHELL=~/.zshrc
-VAULT_ADDR="${VAULT_ADDR=:-http://127.0.0.1:8200}"
+VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8200}"
 
 set +e
 
@@ -34,24 +34,33 @@ case $key in
 esac
 done
 
+function vault_config() {
+  tcctl helpers check_bin_file vault
+  VAULT_ADDR=$1
+  VAULT_NAME=$2
+  VAULT_PASSWORD=$3
+  echo 'export VAULT_ADDR='"$VAULT_ADDR" >> $VAULT_CONFIG_FILE
+  echo 'export VAULT_NAME='"$VAULT_NAME" >> $VAULT_CONFIG_FILE
+  echo 'export VAULT_PASSWORD='"$VAULT_PASSWORD" >> $VAULT_CONFIG_FILE
+  echo "source $VAULT_CONFIG_FILE" >> $COMMAND_SHELL
+  source $VAULT_CONFIG_FILE
+  export _error_code=$?
+  __MSG="Command: tcctl vault config $@"
+  __MSG+="$__output"
+  if [[ $_error_code -eq "0" ]]; then
+    _message "$__MSG" "info" "$_error_code"
+  else
+    _message "$__MSG" "error" "$_error_code"
+  fi
+  echo "Add vault credentials to profile is successfully"
+}
+
 if [ -z "$VAULT_NAME" ]; then
-  __MSG="Command: \033[36mtcctl vault config\033[39m missed --vault-name"
-  _message_error "$__MSG"
+  __MSG="Command: tcctl vault config missed --vault-name"
+  _message "$__MSG" "error" "$_error_code"
 elif [ -z "$VAULT_PASSWORD" ]; then
-  __MSG="Command: \033[36mtcctl vault config\033[39m missed --vault-password"
-  _message_error "$__MSG"
+  __MSG="Command: tcctl vault config missed --vault-password"
+  _message "$__MSG" "error" "$_error_code"
 else
-  function vault_config() {
-    tcctl helpers check_bin_file vault
-    VAULT_ADDR=$1
-    VAULT_NAME=$2
-    VAULT_PASSWORD=$3
-    echo 'export VAULT_ADDR='"$VAULT_ADDR" >> $VAULT_CONFIG_FILE
-    echo 'export VAULT_NAME='"$VAULT_NAME" >> $VAULT_CONFIG_FILE
-    echo 'export VAULT_PASSWORD='"$VAULT_PASSWORD" >> $VAULT_CONFIG_FILE
-    echo "source $VAULT_CONFIG_FILE" >> $COMMAND_SHELL
-    source $VAULT_CONFIG_FILE
-    echo "Add vault credentials to profile is successfully"
-  }
   vault_config "$VAULT_ADDR" "$VAULT_NAME" "$VAULT_PASSWORD"
 fi
diff --git a/tc/app/vault/diff b/tc/app/vault/diff
--- a/tc/app/vault/diff
+++ b/tc/app/vault/diff
@@ -26,26 +26,27 @@ case $key in
 esac
 done
 
+function vault_diff() {
+  tcctl helpers check_bin_file vault
+  ENV1=$1
+  ENV2=$2
+  __output=$( diff -y --suppress-common-lines "$ENV1" "$ENV2" )
+  export _error_code=$?
+  __MSG="Command: tcctl vault diff $@"
+  __MSG+="$__output"
+  if [[ $_error_code -eq "0" ]]; then
+    echo "$__output" | column -t
+  else
+    _message "$__MSG" "error" "$_error_code"
+  fi
+}
+
 if [ -z "$ENV1" ]; then
-  __MSG="Command: \033[36mtcctl vault diff\033[39m missed --env-1"
-  _message_error "$__MSG"
+  __MSG="Command: tcctl vault diff missed --env-1"
+  _message "$__MSG" "error" "$_error_code"
 elif [ -z "$ENV2" ]; then
-  __MSG="Command: \033[36mtcctl vault diff\033[39m missed --env-2"
-  _message_error "$__MSG"
+  __MSG="Command: tcctl vault diff missed --env-2"
+  _message "$__MSG" "error" "$_error_code"
 else
-  function vault_diff() {
-    tcctl helpers check_bin_file vault
-    ENV1=$1
-    ENV2=$2
-    __output=$( diff -y --suppress-common-lines "$ENV1" "$ENV2" )
-    export _error_code=$?
-    __MSG="Command: \033[36mtcctl vault diff $@\033[39m\n"
-    __MSG+="$__output"
-    if [[ $_error_code -eq "0" ]]; then
-      echo "$__output" | column -t
-    else
-      _message "$__MSG" "error" "$_error_code"
-    fi
-  }
   vault_diff "$ENV1" "$ENV2"
 fi
diff --git a/tc/app/vault/get b/tc/app/vault/get
--- a/tc/app/vault/get
+++ b/tc/app/vault/get
@@ -26,27 +26,28 @@ case $key in
 esac
 done
 
+function vault_get() {
+  tcctl helpers check_bin_file vault
+  tcctl vault token
+  VAULT_SECRET=$1
+  ENV_TEMP=$2
+  __output=$( vault kv get "$VAULT_SECRET" 2>&1 )
+  export _error_code=$?
+  __MSG="Command: tcctl vault get $@"
+  __MSG+="$__output"
+  if [ $_error_code -eq "0" ]; then
+    vault kv get "$VAULT_SECRET" | sed 's/\ \{1,\}/=/g' | sed 1,11d > "$ENV_TEMP"
+  else
+    _message "$__MSG" "error" "$_error_code"
+  fi
+}
+
 if [ -z "$SECRET_PROJECT" ]; then
-  __MSG="Command: \033[36mtcctl vault get\033[39m missed --secret-project"
-  _message_error "$__MSG"
+  __MSG="Command: tcctl vault get missed --secret-project"
+  _message "$__MSG" "error" "$_error_code"
 elif [ -z "$ENV_TEMP" ]; then
-  __MSG="Command: \033[36mtcctl vault get\033[39m missed --env-tmp"
-  _message_error "$__MSG"
+  __MSG="Command: tcctl vault get missed --env-tmp"
+  _message "$__MSG" "error" "$_error_code"
 else
-  function vault_get() {
-    tcctl helpers check_bin_file vault
-    tcctl vault token
-    VAULT_SECRET=$1
-    ENV_TEMP=$2
-    __output=$( vault kv get "$VAULT_SECRET" 2>&1 )
-    export _error_code=$?
-    __MSG="Command: \033[36mtcctl vault get $@\033[39m\n"
-    __MSG+="$__output"
-    if [ $_error_code -eq "0" ]; then
-      vault kv get "$VAULT_SECRET" | sed 's/\ \{1,\}/=/g' | sed 1,11d > "$ENV_TEMP"
-    else
-      _message "$__MSG" "error" "$_error_code"
-    fi
-  }
   vault_get "$SECRET_PROJECT" "$ENV_TEMP"
 fi
diff --git a/tc/app/vault/path b/tc/app/vault/path
--- a/tc/app/vault/path
+++ b/tc/app/vault/path
@@ -22,23 +22,24 @@ case $key in
 esac
 done
 
+function vault_check_path() {
+  tcctl helpers check_bin_file vault
+  tcctl vault token
+  SECRET_PATH="$1"
+  __output=$( vault kv get "$SECRET_PATH" 2>&1 )
+  export _error_code=$?
+  __MSG="Command: tcctl vault path $@"
+  __MSG+="$__output"
+  if [ $_error_code -eq "0" ]; then
+    echo "true"
+  else
+    echo "false"
+  fi
+}
+
 if [ -z "$SECRET_PATH" ]; then
-  __MSG="Command: \033[36mtcctl vault path\033[39m missed --secret-path"
-  _message_error "$__MSG"
+  __MSG="Command: tcctl vault path missed --secret-path"
+  _message "$__MSG" "error" "$_error_code"
 else
-  function vault_check_path() {
-    tcctl helpers check_bin_file vault
-    tcctl vault token
-    SECRET_PATH="$1"
-    __output=$( vault kv get "$SECRET_PATH" 2>&1 )
-    export _error_code=$?
-    __MSG="Command: \033[36mtcctl vault path $@\033[39m\n"
-    __MSG+="$__output"
-    if [ $_error_code -eq "0" ]; then
-      echo "true"
-    else
-      echo "false"
-    fi
-  }
   vault_check_path "$SECRET_PATH"
 fi
diff --git a/tc/app/vault/put b/tc/app/vault/put
--- a/tc/app/vault/put
+++ b/tc/app/vault/put
@@ -26,27 +26,28 @@ case $key in
 esac
 done
 
+function vault_put() {
+  tcctl helpers check_bin_file vault
+  tcctl vault token
+  VAULT_SECRETS=$1
+  ENV_FILE=$2
+  __output=$( vault kv put "$VAULT_SECRETS" $(egrep -v '^#' "$ENV_FILE") 2>&1 )
+  export _error_code=$?
+  __MSG="Command: tcctl vault put $@"
+  __MSG+="$__output"
+  if [ $_error_code -eq "0" ]; then
+    _vault_kv_put=$( echo "$__output" | xargs )
+  else
+    _message "$__MSG" "error" "$_error_code"
+  fi
+}
+
 if [ -z "$SECRET_PROJECT" ]; then
-  __MSG="Command: \033[36mtcctl vault put\033[39m missed --secret-project"
+  __MSG="Command: tcctl vault put missed --secret-project"
   _message_error "$__MSG"
 elif [ -z "$ENV" ]; then
-  __MSG="Command: \033[36mtcctl vault put\033[39m missed --env"
-  _message_error "$__MSG"
+  __MSG="Command: tcctl vault put missed --env"
+  _message "$__MSG" "error" "$_error_code"
 else
-  function vault_put() {
-    tcctl helpers check_bin_file vault
-    tcctl vault token
-    VAULT_SECRETS=$1
-    ENV_FILE=$2
-    __output=$( vault kv put "$VAULT_SECRETS" $(egrep -v '^#' "$ENV_FILE") 2>&1 )
-    export _error_code=$?
-    __MSG="Command: \033[36mtcctl vault put $@\033[39m\n"
-    __MSG+="$__output"
-    if [ $_error_code -eq "0" ]; then
-      _vault_kv_put=$( echo "$__output" | xargs )
-    else
-      _message "$__MSG" "error" "$_error_code"
-    fi
-  }
   vault_put "$SECRET_PROJECT" "$ENV"
 fi
