feature : added cert_trust, fix bugs

diff --git a/tc/app/dns/cert_trust b/tc/app/dns/cert_trust
--- a/tc/app/dns/cert_trust
+++ b/tc/app/dns/cert_trust
@@ -3,7 +3,7 @@
 source "$CLI_DIR/tc/framework/functions"
 source "$CLI_DIR/tc/app/dns/functions"
 
-dns_name=
+root_cert_path=
 
 while echo "$1" | grep -q ^--; do
   __key=${1//--/}
@@ -17,4 +17,11 @@ while echo "$1" | grep -q ^--; do
   fi
 done
 
-_cert_gen "$dns_name"
+if [ -f "$root_cert_path" ]; then
+  _cert_trust "$root_cert_path"
+  __error_code=$?
+  if [[ $__error_code -gt "0" ]]; then
+    __MSG="File $root_cert_path doesn't exists"
+    _message "$__MSG" "error" "$__error_code"
+  fi
+fi
diff --git a/tc/app/dns/functions b/tc/app/dns/functions
--- a/tc/app/dns/functions
+++ b/tc/app/dns/functions
@@ -38,3 +38,18 @@ function _cert_gen() {
   _message "Clear directory from cert-gen and cert files"
   rm -rf /tmp/cert-gen/ $$ /tmp/tenantcloud-rootCA.*
 }
+
+function _cert_trust() {
+  __root_cert_path=$1
+  __command="sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $__root_cert_path"
+  __output=$( eval "$__command" )
+  _error_code=$?
+  __MSG="Command: Add trusted root certificate"
+  __MSG+="$__output"
+  if [[ "$_error_code" -eq "0" ]]; then
+    _message "Root certificate successfully trusted "
+  else
+    _message "$__MSG" "error" "$_error_code"
+    exit 1
+  fi
+}
