modify: add new commands and functions v1, changed cert_gen command

diff --git a/tc/app/dns/functions b/tc/app/dns/functions
--- a/tc/app/dns/functions
+++ b/tc/app/dns/functions
@@ -17,26 +17,32 @@ function _get_all_custom_dns_name_from_nginx() {
 
 function _cert_gen() {
   __dns_name=$1
-  __dns_names=$(for i in $( cat /usr/local/etc/nginx/ssl/tc.loc.crt | openssl x509 -text | grep DNS ); do
-                  echo "$i" | sed -e "s/^DNS://" -e "s/,$//"
-                done)
-  __dns_names_result="$__dns_names $__dns_name "\*."$__dns_name"
-  __dns_names=$(echo "$__dns_names_result" | gsed -e "s/ /,/g")
-  _message "Download cert-gen"
+  __dns_names=$2
+  __root_cert_path=$3
+  __root_key_path=$4
+  __cert_path=$5
+  __key_path=$6
+  __csr_path=$7
   git -C /tmp clone https://github.com/devilbox/cert-gen.git
-  _message "Copy root certs to tmp directory"
-  cp -r docs/installation/ssl/tenantcloud-rootCA.* /tmp/
-  _message "Generate cert for ${__dns_name}"
-  /tmp/cert-gen/bin/cert-gen -v -c UA -s Ivano-Frankivsk -l Ivano-Frankivsk -o TC -u TC \
-             -n tc.loc -e i.bronovskyi@root.devops \
-             -a "${__dns_names}" \
-             /tmp/tenantcloud-rootCA.key \
-             /tmp/tenantcloud-rootCA.crt \
-             /tmp/tc.loc.key \
-             /tmp/tc.loc.csr \
-             /tmp/tc.loc.crt >> /dev/null
-  _message "Clear directory from cert-gen and cert files"
-  rm -rf /tmp/cert-gen/ $$ /tmp/tenantcloud-rootCA.*
+  __command="/tmp/cert-gen/bin/cert-gen -v -c UA -s Ivano-Frankivsk -l Ivano-Frankivsk -o TC -u TC \
+             -n ${__dns_name} -e i.bronovskyi@root.devops \
+             -a ${__dns_names} \
+             ${__root_key_path} \
+             ${__root_cert_path} \
+             ${__key_path} \
+             ${__csr_path} \
+             ${__cert_path} >> /dev/null"
+  __output=$( eval "$__command" )
+  _error_code=$?
+  rm -rf /tmp/cert-gen/
+  __MSG="Command: Generate certificate for ${__dns_names} "
+  __MSG+="$__output"
+  if [[ "$_error_code" -eq "0" ]]; then
+    _message "Generate certificate for ${__dns_names} is successfully"
+  else
+    _message "$__MSG" "error" "$_error_code"
+    exit 1
+  fi
 }
 
 function _cert_trust() {
@@ -44,11 +50,27 @@ function _cert_trust() {
   __command="sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $__root_cert_path"
   __output=$( eval "$__command" )
   _error_code=$?
-  __MSG="Command: Add trusted root certificate"
+  __MSG="Command: Add trusted root certificate "
   __MSG+="$__output"
   if [[ "$_error_code" -eq "0" ]]; then
-    _message "Root certificate successfully trusted "
+    _message "Root certificate successfully trusted"
   else
+    _message "$__MSG" "error" "$_error_code"
+    exit 1
+  fi
+}
+
+function _get_all_local_dns() {
+  __cert_path=$1
+  __command=$(for i in $( cat "$__cert_path" | openssl x509 -text | grep DNS ); do
+                echo "$i" | sed -e "s/^DNS://" -e "s/,$//"
+              done)
+  _error_code=$?
+  # shellcheck disable=SC2086
+  echo $__command
+  __MSG="Command: Get all local domains name "
+  __MSG+="$__command"
+  if [[ "$_error_code" -gt "0" ]]; then
     _message "$__MSG" "error" "$_error_code"
     exit 1
   fi
diff --git a/tc/app/helpers/functions b/tc/app/helpers/functions
--- a/tc/app/helpers/functions
+++ b/tc/app/helpers/functions
@@ -20,12 +20,28 @@ function _replace_string() {
   if ! grep -q "$__replace_string" "$__file_to_edit"; then
     __output=$(eval "$__command")
     _error_code=$?
-    __MSG="Command: replace $1 in $3 file"
+    __MSG="Command: replace $__find_string in $__file_to_edit file"
     __MSG+="$__output"
   fi
   if [[ "$_error_code" -eq "0" ]]; then
     _message "String $1 was replacing in $3 file"
   else
+    _message "$__MSG" "error" "$_error_code"
+    exit 1
+  fi
+}
+
+function _replace_symbol() {
+  __find_symbol=$1
+  __replace_symbol=$2
+  __string_to_edit=$3
+  __command="echo $__string_to_edit | $(_get_sed_symbol) 's/$__replace_symbol/$__find_symbol/g'"
+  __output=$(eval "$__command")
+  _error_code=$?
+  __MSG="Command: symbol $__find_symbol replace in $__string_to_edit"
+  __MSG+="$__output"
+  echo "$__output"
+  if [[ "$_error_code" -gt "0" ]]; then
     _message "$__MSG" "error" "$_error_code"
     exit 1
   fi
@@ -40,11 +56,11 @@ function _append_string_after() {
   if ! grep -q "$__replace_string" "$__file_to_edit"; then
     __output=$( eval "$__command" )
     _error_code=$?
-    __MSG="Command: replace $1 in $3 file"
+    __MSG="Command: replace $__find_string in $__file_to_edit file"
     __MSG+="$__output"
   fi
   if [[ "$_error_code" -eq "0" ]]; then
-    _message "String $1 was replacing in $3 file"
+    _message "String $__find_string was replacing in $__file_to_edit file"
   else
     _message "$__MSG" "error" "$_error_code"
     exit 1
@@ -59,12 +75,8 @@ function _replace_string_with_escapes() {
   __command+="'s+$__find_string+$__replace_string+' $__file_to_edit"
   __output=$(eval "$__command")
   _error_code=$?
-  __MSG="Command: replace $1 in $3 file"
+  __MSG="Command: replace $__find_string in $__file_to_edit file"
   __MSG+="$__output"
-  if [[ "$_error_code" -ne "0" ]]; then
-    echo "Error -" "$__command"
-    exit 1
-  fi
   if [[ "$_error_code" -eq "0" ]]; then
     _message "String $1 was replacing in $3 file"
   else
@@ -80,10 +92,10 @@ function _delete_string() {
   __command+="'/$__delete_string/d' $__file_to_edit"
   __output=$(eval "$__command")
   _error_code=$?
-  __MSG="Command: String $1 was deleting in $3 file"
+  __MSG="Command:  delete $__delete_string in $__file_to_edit file"
   __MSG+="$__output"
   if [[ "$_error_code" -eq "0" ]]; then
-    _message "String $1 was replacing in $3 file"
+    _message "String $__delete_string was deleting in $__file_to_edit file"
   else
     _message "$__MSG" "error" "$_error_code"
     exit 1
@@ -97,11 +109,11 @@ function _insert_string() {
   if ! grep "$__insert_string" "$__file_to_edit"; then
     __output=$(eval "$__command")
     _error_code=$?
-    __MSG="Command: Insert $1 in $2 file"
+    __MSG="Command: Insert $__insert_string in $__file_to_edit file"
     __MSG+="$__output"
   fi
   if [[ "$_error_code" -eq "0" ]]; then
-    _message "String $1 was inserting in $2 file"
+    _message "String $__insert_string was inserting in $__file_to_edit file"
   else
     _message "$__MSG" "error" "$_error_code"
     exit 1
@@ -116,11 +128,9 @@ function _append_string_yaml() {
   yq e '${__yaml_path} += env(__dns_name)' -i ${__file_name}"
   __output=$(eval "$__command")
   _error_code=$?
-  __MSG="Command: Insert $2 in $3 file"
+  __MSG="Command: Insert $__yaml_value in $__file_name file"
   __MSG+="$__output"
-  if [[ "$_error_code" -eq "0" ]]; then
-    _message "String $2 was inserting in $3 file"
-  else
+  if [[ "$_error_code" -gt "0" ]]; then
     _message "$__MSG" "error" "$_error_code"
     exit 1
   fi
@@ -134,6 +144,8 @@ function _check_string_yaml() {
   yq eval '${__yaml_path}| select(. == env(__dns_name))' ${__file_name}"
   __output=$(eval "$__command")
   _error_code=$?
+  __MSG="Command: check $__yaml_value in $__file_name file"
+  __MSG+="$__output"
   echo "$__output"
   if [[ "$_error_code" -gt "0" ]]; then
     _message "$__MSG" "error" "$_error_code"
@@ -149,5 +161,16 @@ function _get_sed() {
     __output=$(command -v "sed")
   fi
   __output+=" -i "
+  echo "$__output"
+}
+
+function _get_sed_symbol() {
+  __OS=$(uname -s)
+  if [[ $__OS == "Darwin" ]]; then
+    __output=$(command -v "gsed")
+  else
+    __output=$(command -v "sed")
+  fi
+  __output+=" -e "
   echo "$__output"
 }
