config: added new method of authorization, code refactoring

diff --git a/tc/app/vault/file/download b/tc/app/vault/file/download
--- a/tc/app/vault/file/download
+++ b/tc/app/vault/file/download
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# shellcheck disable=SC1091,SC2119
+# shellcheck disable=SC1091
 
 source "$CLI_DIR/tc/framework/functions"
 source "$CLI_DIR/tc/app/vault/functions"
@@ -8,45 +8,42 @@ source "$CLI_DIR/tc/app/helpers/functions"
 
 set -o pipefail
 
-while [[ $# -gt 0 ]]
-do
-key="$1"
+auth_type=
+secret_path=
+file=
+vault_token=
+vault_name=
+vault_pass=
+vault_address=
 
-case $key in
-    --secret-path)
-    SECRET_PATH="$2"
+while echo "$1" | grep -q ^--; do
+  __key=${1//--/}
+  __key=${__key//-/_}
+  if [[ -n "$2" ]]; then
+    eval "${__key}"='$2'
     shift 2
-    ;;
-    --file)
-    FILE="$2"
-    shift 2
-    ;;
-    *)
-    ;;
-esac
+  else
+    set "${__key}"
+    shift
+  fi
 done
 
-function _vault_download() {
-  _check_bin_file vault
-  VAULT_TOKEN=$(_vault_get_token)
-  export VAULT_TOKEN
-  __secret_path=$1
-  __file=$2
-  rm -rf "$__file"
-  if [ "$__secret_path" ] ; then
-    __output=$( vault read "$__secret_path" -format=json | jq -r .data.key >> "$__file" )
-    _error_code=$?
-    __MSG="Command: tcctl vault download $__file from vault server "
-    __MSG+="$__output"
-    if [ "$_error_code" -eq "0" ]; then
-      echo "Success! Data downloaded: $__secret_path -> $__file"
-    fi
-  fi
-}
-
-if [ -z "$FILE" ]; then
-  __MSG="Command: tcctl vault file download missed --file"
-  _message "$__MSG" "error" "$_error_code"
+_check_bin_file vault
+if [[ "$auth_type" = "userpass" ]]; then
+  _vault_authorization "$auth_type" "$vault_name" "$vault_pass" "$vault_address"
+elif [[ "$auth_type" = "token" ]]; then
+  _vault_authorization "$auth_type" "$vault_token" "$vault_address"
 else
-  _vault_download "$SECRET_PATH" "$FILE"
+  _vault_authorization
+fi
+rm -rf "$file"
+if [ "$secret_path" ] ; then
+  vault read "$secret_path" -format=json | jq -r .data.key >> "$file"
+  _error_code=$?
+  if [ "$_error_code" -eq "0" ]; then
+    echo "Downloading $file from $secret_path is successfully"
+  else
+    __MSG="Error while downloading $file from $secret_path"
+    _message "$__MSG" "error" "$_error_code"
+  fi
 fi
diff --git a/tc/app/vault/functions b/tc/app/vault/functions
--- a/tc/app/vault/functions
+++ b/tc/app/vault/functions
@@ -13,9 +13,6 @@ function _vault_get_addr() {
   echo "$VAULT_ADDR"
 }
 
-VAULT_ADDR="$(_vault_get_addr)"
-export VAULT_ADDR
-
 function _vault_kv_list() {
   __secret_path="$1"
   __output=$(vault kv list "$__secret_path" 2>&1)
@@ -27,17 +24,47 @@ function _vault_kv_list() {
   fi
 }
 
-function _vault_get_token()  {
+function _vault_authorization()  {
   _check_bin_file vault
-  VAULT_CONFIG_FILE=~/.vault-configuration
-  source $VAULT_CONFIG_FILE
-  __output=$(vault login -method=userpass username="$VAULT_NAME" password="$VAULT_PASSWORD")
-  _error_code=$?
-  if [ "$_error_code" -eq "0" ]; then
-    VAULT_TOKEN=$( echo "$__output" | sed 1,6d | tr -s ' ' | cut -f 2 -d ' ' | sed -n 1p )
-    echo "$VAULT_TOKEN"
+  __auth_type=$1
+  if [[ "$__auth_type" = "userpass" ]]; then
+    __vault_name=$2
+    __vault_password=$3
+    export VAULT_ADDR=$4
+    __output=$(vault login -method=userpass username="$__vault_name" password="$__vault_password")
+    _error_code=$?
+    if [ "$_error_code" -eq "0" ]; then
+      VAULT_TOKEN=$(echo "$__output" | sed 1,6d | tr -s ' ' | cut -f 2 -d ' ' | sed -n 1p)
+      export VAULT_TOKEN
+    else
+      __MSG="Error while creating vault token"
+      _message "$__MSG" "error" "$_error_code"
+    fi
+  elif [[ "$__auth_type" = "token" ]]; then
+    __vault_token=$2
+    export VAULT_ADDR=$3
+    __output=$(vault login token="$__vault_token")
+    _error_code=$?
+    if [ "$_error_code" -eq "0" ]; then
+      VAULT_TOKEN=$(echo "$__output" | sed 1,6d | tr -s ' ' | cut -f 2 -d ' ' | sed -n 1p)
+      export VAULT_TOKEN
+    else
+      __MSG="Error while creating vault token"
+      _message "$__MSG" "error" "$_error_code"
+    fi
   else
-    __MSG="Error while creating vault token"
-    _message "$__MSG" "error" "$_error_code"
+    VAULT_CONFIG_FILE=~/.vault-configuration
+    source $VAULT_CONFIG_FILE
+    VAULT_ADDR="$(_vault_get_addr)"
+    export VAULT_ADDR
+    __output=$(vault login -method=userpass username="$VAULT_NAME" password="$VAULT_PASSWORD")
+    _error_code=$?
+    if [ "$_error_code" -eq "0" ]; then
+      VAULT_TOKEN=$(echo "$__output" | sed 1,6d | tr -s ' ' | cut -f 2 -d ' ' | sed -n 1p)
+      export VAULT_TOKEN
+    else
+      __MSG="Error while creating vault token"
+      _message "$__MSG" "error" "$_error_code"
+    fi
   fi
 }
diff --git a/tc/app/vault/get b/tc/app/vault/get
--- a/tc/app/vault/get
+++ b/tc/app/vault/get
@@ -1,13 +1,18 @@
 #!/usr/bin/env bash
 
-# shellcheck disable=SC2124,SC1091,SC2119
+# shellcheck disable=SC1091
 
 source "$CLI_DIR/tc/framework/functions"
 source "$CLI_DIR/tc/app/vault/functions"
 source "$CLI_DIR/tc/app/helpers/functions"
 
+auth_type=
 secret_path=
 env=
+vault_token=
+vault_name=
+vault_pass=
+vault_address=
 
 while echo "$1" | grep -q ^--; do
   __key=${1//--/}
@@ -21,21 +26,19 @@ while echo "$1" | grep -q ^--; do
   fi
 done
 
-function _vault_get() {
-  _check_bin_file vault
-  VAULT_TOKEN=$(_vault_get_token)
-  export VAULT_TOKEN
-  __secret_path=$1
-  __local_path=$2
-  __output=$(vault kv get "$__secret_path" 2>&1)
-  _error_code=$?
-  __MSG="Get keys from ${__secret_path} - "
-  __MSG+="$__output"
-  if [ "$_error_code" -eq "0" ]; then
-    vault kv get "$__secret_path" | sed 's/\ \{1,\}/=/g'| sed 's:=n/a$:=:' | sed 1,11d > "$__local_path"
-  else
-    _message "$__MSG" "error" "$_error_code"
-  fi
-}
-
-_vault_get "$secret_path" "$env"
+_check_bin_file vault
+if [[ "$auth_type" = "userpass" ]]; then
+  _vault_authorization "$auth_type" "$vault_name" "$vault_pass" "$vault_address"
+elif [[ "$auth_type" = "token" ]]; then
+  _vault_authorization "$auth_type" "$vault_token" "$vault_address"
+else
+  _vault_authorization
+fi
+vault kv get "$secret_path" > /dev/null 2>&1
+_error_code=$?
+if [ "$_error_code" -eq "0" ]; then
+  vault kv get "$secret_path" | sed 's/\ \{1,\}/=/g'| sed 's:=n/a$:=:' | sed 1,11d > "$env"
+else
+  __MSG="Get keys from ${secret_path} to ${env}"
+  _message "$__MSG" "error" "$_error_code"
+fi
diff --git a/tc/app/vault/put b/tc/app/vault/put
--- a/tc/app/vault/put
+++ b/tc/app/vault/put
@@ -1,51 +1,42 @@
 #!/usr/bin/env bash
 
-# shellcheck disable=SC2196,SC2046,SC2124,SC2034,SC1091,SC2119
+# shellcheck disable=SC2196,SC2046,SC1091,SC2119
 
 source "$CLI_DIR/tc/framework/functions"
 source "$CLI_DIR/tc/app/vault/functions"
 source "$CLI_DIR/tc/app/helpers/functions"
 
-while [[ $# -gt 0 ]]
-do
-key="$1"
+auth_type=
+secret_path=
+env=
+vault_token=
+vault_name=
+vault_pass=
+vault_address=
 
-case $key in
-    --secret-path)
-    SECRET_PATH="$2"
+while echo "$1" | grep -q ^--; do
+  __key=${1//--/}
+  __key=${__key//-/_}
+  if [[ -n "$2" ]]; then
+    eval "${__key}"='$2'
     shift 2
-    ;;
-    --env)
-    ENV="$2"
-    shift 2
-    ;;
-    *)
-    ;;
-esac
+  else
+    set "${__key}"
+    shift
+  fi
 done
 
-function _vault_put() {
-  _check_bin_file vault
-  VAULT_TOKEN=$(_vault_get_token)
-  export VAULT_TOKEN
-  __secret_path=$1
-  __env=$2
-  __output=$(vault kv put "$__secret_path" $(egrep -v '^#' "$__env") 2>&1)
-  _error_code=$?
-  if [ "$_error_code" -eq "0" ]; then
-    _vault_kv_put=$(echo "$__output" | xargs)
-  else
-    __MSG="Put to $__secret_path error"
-    _message "$__MSG" "error" "$_error_code"
-  fi
-}
-
-if [ -z "$SECRET_PATH" ]; then
-  __MSG="Command: tcctl vault put missed --secret-path"
-  _message_error "$__MSG"
-elif [ -z "$ENV" ]; then
-  __MSG="Command: tcctl vault put missed --env"
-  _message "$__MSG" "error" "$_error_code"
+_check_bin_file vault
+if [[ "$auth_type" = "userpass" ]]; then
+  _vault_authorization "$auth_type" "$vault_name" "$vault_pass" "$vault_address"
+elif [[ "$auth_type" = "token" ]]; then
+  _vault_authorization "$auth_type" "$vault_token" "$vault_address"
 else
-  _vault_put "$SECRET_PATH" "$ENV"
+  _vault_authorization
+fi
+vault kv put "$secret_path" $(egrep -v '^#' "$env") > /dev/null 2>&1
+_error_code=$?
+if [ "$_error_code" -gt "0" ]; then
+  __MSG="Error while put to $secret_path"
+  _message "$__MSG" "error" "$_error_code"
 fi
diff --git a/tc/app/vault/secrets/create b/tc/app/vault/secrets/create
--- a/tc/app/vault/secrets/create
+++ b/tc/app/vault/secrets/create
@@ -1,48 +1,42 @@
 #!/usr/bin/env bash
 
-# shellcheck disable=SC2086,SC1091,SC2119
+# shellcheck disable=SC2086,SC1091
 
 source "$CLI_DIR/tc/framework/functions"
 source "$CLI_DIR/tc/app/vault/functions"
 source "$CLI_DIR/tc/app/helpers/functions"
 
-KV_VERSION="2 kv"
+kv_version="${kv_version:-2 kv}"
+auth_type=
+secret_path=
+vault_token=
+vault_name=
+vault_pass=
+vault_address=
 
-while [[ $# -gt 0 ]]
-do
-key="$1"
-
-case $key in
-    --secret_path)
-    SECRET_PATH="$2"
+while echo "$1" | grep -q ^--; do
+  __key=${1//--/}
+  __key=${__key//-/_}
+  if [[ -n "$2" ]]; then
+    eval "${__key}"='$2'
     shift 2
-    ;;
-    --kv_version)
-    KV_VERSION="$2"
-    shift 2
-    ;;
-    *)
-    ;;
-esac
+  else
+    set "${__key}"
+    shift
+  fi
 done
 
-function _secret_create() {
-  _check_bin_file vault
-  VAULT_TOKEN=$(_vault_get_token)
-  export VAULT_TOKEN
-  __secret_path=$1
-  __kv_version=$2
-  vault secrets enable -path=$__secret_path -version=$__kv_version
-  _error_code=$?
-  if [ $_error_code -gt "0" ]; then
-    __MSG="Error while creating $__secret_path"
-    _message "$__MSG" "error" "$_error_code"
-  fi
-}
-
-if [ -z "$SECRET_PATH" ]; then
-  __MSG="Command: tcctl vault secret create missed --secret_path"
-  _message "$__MSG" "error" "$_error_code"
+_check_bin_file vault
+if [[ "$auth_type" = "userpass" ]]; then
+  _vault_authorization "$auth_type" "$vault_name" "$vault_pass" "$vault_address"
+elif [[ "$auth_type" = "token" ]]; then
+  _vault_authorization "$auth_type" "$vault_token" "$vault_address"
 else
-  _secret_create "$SECRET_PATH" "$KV_VERSION"
+  _vault_authorization
+fi
+vault secrets enable -path=$secret_path -version=$kv_version > /dev/null 2>&1
+_error_code=$?
+if [ $_error_code -gt "0" ]; then
+  __MSG="Error while creating $secret_path"
+  _message "$__MSG" "error" "$_error_code"
 fi
diff --git a/tc/app/vault/secrets/path/delete b/tc/app/vault/secrets/path/delete
--- a/tc/app/vault/secrets/path/delete
+++ b/tc/app/vault/secrets/path/delete
@@ -1,12 +1,17 @@
 #!/usr/bin/env bash
 
-# shellcheck disable=SC1091,SC2119
+# shellcheck disable=SC1091
 
 source "$CLI_DIR/tc/framework/functions"
-source "$CLI_DIR/tc/app/helpers/functions"
 source "$CLI_DIR/tc/app/vault/functions"
+source "$CLI_DIR/tc/app/helpers/functions"
 
+auth_type=
 secret_path=
+vault_token=
+vault_name=
+vault_pass=
+vault_address=
 
 while echo "$1" | grep -q ^--; do
   __key=${1//--/}
@@ -20,17 +25,17 @@ while echo "$1" | grep -q ^--; do
   fi
 done
 
-function _secret_delete() {
-  _check_bin_file vault
-  VAULT_TOKEN=$(_vault_get_token)
-  export VAULT_TOKEN
-  __secret_path=$1
-  vault kv metadata delete "$__secret_path"
-  _error_code=$?
-  if [ $_error_code -gt "0" ]; then
-    __MSG="Error while deleting $__secret_path"
-    _message "$__MSG" "error" "$_error_code"
-  fi
-}
-
-_secret_delete "$secret_path"
+_check_bin_file vault
+if [[ "$auth_type" = "userpass" ]]; then
+  _vault_authorization "$auth_type" "$vault_name" "$vault_pass" "$vault_address"
+elif [[ "$auth_type" = "token" ]]; then
+  _vault_authorization "$auth_type" "$vault_token" "$vault_address"
+else
+  _vault_authorization
+fi
+vault kv metadata delete "$secret_path" > /dev/null 2>&1
+_error_code=$?
+if [ $_error_code -gt "0" ]; then
+  __MSG="Error while deleting $secret_path"
+  _message "$__MSG" "error" "$_error_code"
+fi
