fix: Add checker for slack binary file

diff --git a/tc/app/slack/file_upload b/tc/app/slack/file_upload
--- a/tc/app/slack/file_upload
+++ b/tc/app/slack/file_upload
@@ -30,6 +30,7 @@ esac
 done
 
 function slack_file_upload() {
+  if [[ -f $(command -v slack) ]]; then
     __output=$( slack file upload "$3" "$1" --comment "$2" )
     _error_code=$?
     __MSG="Command: tcctl slack file_upload"
@@ -39,6 +40,10 @@ function slack_file_upload() {
     else
       _message "$__MSG" "warning"
     fi
+  else
+    echo "We can't find slack command"
+    exit 1
+  fi
 }
 
 slack_file_upload "$CHANNEL" "$MESSAGE" "$FILE"
diff --git a/tc/app/slack/send_message b/tc/app/slack/send_message
--- a/tc/app/slack/send_message
+++ b/tc/app/slack/send_message
@@ -30,6 +30,7 @@ esac
 done
 
 function slack_send_message() {
+  if [[ -f $(command -v slack) ]]; then
     _slack_message="$1"
     _slack_color="$3"
     _slack_channel="$2"
@@ -46,6 +47,10 @@ function slack_send_message() {
     else
       _message "$__MSG" "error" "$_error_code"
     fi
+  else
+    echo "We can't find slack command"
+    exit 1
+  fi
 }
 
 slack_send_message "$MESSAGE" "$CHANNEL" "$COLOR"
