Fix: Move file_upload to functions file

diff --git a/tc/app/slack/functions b/tc/app/slack/functions
--- a/tc/app/slack/functions
+++ b/tc/app/slack/functions
@@ -26,3 +26,23 @@ function slack_send_message() {
   fi
 }
 
+function slack_file_upload() {
+  if [[ -f $(command -v slack) ]] && [[ -f "$FILE" ]]; then
+    __slack_channel="$1"
+    __slack_message="$2"
+    __slack_file="$3"
+    __output=$( slack file upload "$__slack_file" "$__slack_channel" --comment "$__slack_message" )
+    _error_code=$?
+    __MSG="Command: tcctl slack file_upload"
+    __MSG+="$__output"
+    if [[ "$_error_code" -eq "0" ]]; then
+      _message "Message was send into Slack $CHANNEL"
+    else
+      _message "$__MSG" "warning"
+    fi
+  else
+    echo "We can't find slack command or commnts_summary file"
+    exit 1
+  fi
+}
+
